version: '3.6'

networks:
  api:
    driver: bridge

services:

  caddy:
    image: caddy:2.1.1-alpine
    depends_on:
      - "mongo"
      - "postgres"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ../data/caddy:/data
    networks:
      - api

  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 2021:27017
    volumes:
      - ../data/mongo:/bitnami/mongodb
    networks:
      - api
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASS}
      MONGODB_DATABASE: ${MONGO_DB}

  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - 2023:6379
    volumes:
      - ../data/redis:/bitnami/redis
    networks:
      - api
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}