version: '3.6'

services:

  caddy:
    image: caddy:2.1.1-alpine
    depends_on:
      - "mongo"
      - "postgres"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ../data/caddy:/data

  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 2021:27017
    volumes:
      - ../data/mongo:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASS}
      MONGODB_DATABASE: ${MONGO_DB}

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 2022:5432
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_ADMIN}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASS}
      HASURA_POSTGRES_USER: ${POSTGRES_API_USER}
      HASURA_POSTGRES_PASS: ${POSTGRES_API_PASS}